---
- name: Change file owner and group
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /home/dsp/bin/
      owner: dsp
      group: dsp
      mode: '755'
      state: directory
      recurse: true
