---
- name: Stop and disable service
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Stop and disable service
    ansible.builtin.service:
      name: bluetooth
      state: stopped
      enabled: no
